stages:
    - image
    - test
    - build
    - publish

variables:
    DOCKER_REGISTRY: "reg.nic.cz"
    # Set up pip cache shared between all jobs of the project.
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PIP_INDEX_URL:
        value: "https://pypi.nic.cz/cznic/public"
        description: "PyPI index to be used."
    POSTGRES_DB: testdb
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
    # Setting PGHOST breaks startup of postgres service
    PGDATABASE: testdb
    PGUSER: user
    PGPASSWORD: password
    PYTHONWARNINGS: ""

cache:
    paths:
        - .cache/pip

########################################################################################################################
# Docker
.image:
    stage: image
    before_script:
        - docker info
    script:
        # Login to GitLab container registry https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#using-the-gitlab-container-registry
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build --pull --build-arg PYTHON_VERSION=$PYTHON_VERSION --tag "$IMAGE_TAG" --file docker/python/Dockerfile .
        - docker push "$IMAGE_TAG"
    tags:
        - dind
    variables:
        IMAGE_TAG: "$CI_REGISTRY_IMAGE/tox:$PYTHON_VERSION"

image:py37:
    extends: .image
    variables:
        PYTHON_VERSION: "3.7"

image:py38:
    extends: .image
    variables:
        PYTHON_VERSION: "3.8"

image:py39:
    extends: .image
    variables:
        PYTHON_VERSION: "3.9"

image:py310:
    extends: .image
    variables:
        PYTHON_VERSION: "3.10"

image:node14:
    extends: .image
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - docker build --pull --tag "$IMAGE_TAG" docker/node
        - docker push "$IMAGE_TAG"
    variables:
        IMAGE_TAG: $CI_REGISTRY_IMAGE/node:14

########################################################################################################################
# Basic declarations
.py37: &py37
    image: "$CI_REGISTRY_IMAGE/tox:3.7"

.py38: &py38
    image: "$CI_REGISTRY_IMAGE/tox:3.8"

.py39: &py39
    image: "$CI_REGISTRY_IMAGE/tox:3.9"

.py310: &py310
    image: "$CI_REGISTRY_IMAGE/tox:3.10"

.node: &node
    stage: test
    image: "$CI_REGISTRY/$CI_PROJECT_PATH/node:14"

.test: &test
    stage: test
    services:
        - name: postgres:12
          alias: django-pain-postgres
          command: ["postgres", "-c", "fsync=off"]
    before_script:
        - echo "Active index - $PIP_INDEX_URL"
    script:
        # Can't set PGHOST as a job variable, it breaks postgres service startup.
        - PGHOST=django-pain-postgres tox
    coverage: '/TOTAL(?:\s+\d+){4}\s+(\d+\%)/'
    interruptible: true

########################################################################################################################
# Individual jobs
licensing:
    image: "$DOCKER_REGISTRY/utils/license-check:latest"
    tags:
        - common
    script:
        - license-check -v

test:py37:
    <<: *test
    <<: *py37
    needs: ["image:py37"]

test:py38:
    <<: *test
    <<: *py38
    needs: ["image:py38"]

test:py39:
    <<: *test
    <<: *py39
    needs: ["image:py39"]

test:py310:
    <<: *test
    <<: *py310
    needs: ["image:py310"]

test:node14:
    <<: *node
    before_script:
        - node --version
        - npm --version
        - npm clean-install
        - npm list || true
    script:
        - npm run check-css
        - npm run check-js -- --max-warnings=0
        - npm run test
        - npm run build
        - json-python-coverage coverage-js/coverage-summary.json
    needs: ["image:node14"]
