# Generated by Django 2.0.4 on 2018-05-10 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsymbols',
            name='id',
        ),
        migrations.AlterField(
            model_name='paymentsymbols',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='symbols', serialize=False, to='django_pain.BankPayment'),
        ),
    ]
