# Generated by Django 2.0.4 on 2018-05-15 09:05

from django.db import migrations, models
import django_pain.constants


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0002_auto_20180510_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpayment',
            name='state',
            field=models.TextField(choices=[(django_pain.constants.PaymentState('imported'), 'imported'), (django_pain.constants.PaymentState('processed'), 'processed'), (django_pain.constants.PaymentState('exported'), 'exported')], default=django_pain.constants.PaymentState('imported'), verbose_name='Payment state'),
        ),
    ]
