# Generated by Django 2.0.6 on 2018-06-12 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0007_generate_bankpayment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpayment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
