# Generated by Django 2.0.6 on 2018-07-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0008_fix_bankpayment_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='objective',
            field=models.TextField(blank=True, verbose_name='Objective'),
        ),
        migrations.AddField(
            model_name='bankpayment',
            name='processor',
            field=models.TextField(blank=True, verbose_name='Processor'),
        ),
    ]
