# Generated by Django 2.0.7 on 2018-08-13 03:42

from django.db import migrations, models
import django_pain.constants


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0011_alter_bankpayment_account_and_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(unique=True, verbose_name='Invoice number')),
                ('remote_id', models.IntegerField()),
                ('invoice_type', models.TextField(choices=[(django_pain.constants.InvoiceType('advance'), 'advance'), (django_pain.constants.InvoiceType('account'), 'account')], verbose_name='Invoice type')),
                ('payments', models.ManyToManyField(related_name='invoices', to='django_pain.BankPayment')),
            ],
        ),
    ]
