# Generated by Django 2.1 on 2018-08-29 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0013_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankpayment',
            name='objective',
        ),
    ]
