# Generated by Django 2.1 on 2018-10-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0014_remove_bankpayment_objective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpayment',
            name='counter_account_name',
            field=models.TextField(blank=True, db_index=True, verbose_name='Counter account name'),
        ),
        migrations.AlterField(
            model_name='bankpayment',
            name='description',
            field=models.TextField(blank=True, db_index=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bankpayment',
            name='variable_symbol',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Variable symbol'),
        ),
    ]
