# Generated by Django 2.0.9 on 2018-11-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0015_add_search_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.TextField(unique=True, verbose_name='Account number'),
        ),
    ]
