# Generated by Django 2.1.5 on 2019-03-26 09:55

from django.db import migrations, models
import django_pain.constants


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0017_bankpayment_processing_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpayment',
            name='processing_error',
            field=models.TextField(blank=True, choices=[(django_pain.constants.PaymentProcessingError('duplicity'), 'Duplicate payment'), (django_pain.constants.PaymentProcessingError('insufficient_amount'), 'Received amount is lower than expected'), (django_pain.constants.PaymentProcessingError('excessive_amount'), 'Received amount is greater than expected'), (django_pain.constants.PaymentProcessingError('overdue'), 'Payment is overdue'), (django_pain.constants.PaymentProcessingError('manually_broken'), 'Payment was manually broken'), (django_pain.constants.PaymentProcessingError('too_old'), "Payment is older than 15 days, it can't be processed automatically")], null=True, verbose_name='Automatic processing error'),
        ),
    ]
