# Generated by Django 2.1.5 on 2019-06-06 07:49

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0018_update_bankpayment_processing_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpayment',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=10, max_digits=64, verbose_name='Amount'),
        ),
    ]
