# Generated by Django 2.2.11 on 2020-06-03 15:53

from django.db import migrations, models
import django_pain.constants


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0020_27622_card_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpayment',
            name='state',
            field=models.TextField(choices=[(django_pain.constants.PaymentState('initialized'), 'initialized'), (django_pain.constants.PaymentState('ready_to_process'), 'ready to process'), (django_pain.constants.PaymentState('processed'), 'processed'), (django_pain.constants.PaymentState('deferred'), 'not identified'), (django_pain.constants.PaymentState('exported'), 'exported'), (django_pain.constants.PaymentState('canceled'), 'canceled')], db_index=True, default=django_pain.constants.PaymentState('ready_to_process'), verbose_name='Payment state'),
        ),
        migrations.AlterField(
            model_name='bankpayment',
            name='transaction_date',
            field=models.DateField(db_index=True, null=True, verbose_name='Transaction date'),
        ),
    ]
