# Generated by Django 2.2.14 on 2020-08-04 11:22

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0021_27658_card_payments_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=djmoney.models.fields.CurrencyField(default='CZK', max_length=3),
        ),
        migrations.AlterField(
            model_name='bankpayment',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('CZK', 'Czech Koruna'), ('EUR', 'Euro')], default='CZK', editable=False, max_length=3),
        ),
    ]
