# Generated by Django 2.2.14 on 2021-03-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0022_auto_20200804_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentImportHistory',
            options={'verbose_name': 'Payment Import History', 'verbose_name_plural': 'Payment Import History'},
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.TextField(help_text='Key of PAIN_DOWNLOADERS setting.', verbose_name='Origin')),
                ('start_datetime', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Import start time.', verbose_name='Import start time')),
                ('_filenames', models.TextField(help_text='Names of the files the data were imported from if known.', verbose_name='File names', null=True, blank=True)),
                ('errors', models.PositiveSmallIntegerField(help_text='Number of payments skipped due to an error.', verbose_name='Errors', null=True, blank=True)),
                ('finished', models.BooleanField(default=False, help_text='Indicates whether the import command finished without raising an error.', verbose_name='Finished')),
            ],
        ),
    ]
