# Generated by Django 2.2.20 on 2021-08-04 13:36

from django.db import migrations, models
import django_pain.constants


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0023_paymentimporthistory'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankpayment',
            name='payment_counter_account_only_for_transfer',
        ),
        migrations.AddConstraint(
            model_name='bankpayment',
            constraint=models.CheckConstraint(check=models.Q(('payment_type', django_pain.constants.PaymentType('transfer')), models.Q(('counter_account_number__exact', ''), ('payment_type', django_pain.constants.PaymentType('card_payment'))), _connector='OR'), name='payment_counter_account_only_for_transfer'),
        ),
    ]
