# Generated by Django 2.2.20 on 2021-12-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0025_bankaccount_enforce_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='enforce_currency',
            field=models.BooleanField(default=True, help_text="When this option is set it is not possible to create payments to this account with currency different from the account's currency.", verbose_name='Enforce currency check'),
        ),
    ]
