# Generated by Django 2.2.20 on 2021-12-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_pain', '0026_auto_20211206_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='enforce_currency',
        ),
    ]
